# Site settings
title: Interim ledning inom Tech
email: hello@sandstre.am
url: https://www.sandstream.am
description: "<p>Peter Sandström är i framkanten av digital strategi och teknisk innovation, och han leder företag genom den dynamiska digitala eran med djupgående expertis och strategisk insikt.</p>"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#40E0D0'
  pink: '#FF1493'
  violet: '#9400D3'
  coral: '#FF6B6B'
  blue: '#0000FF'

# Footer settings
footer: SANDSTREAM AB 
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sandstream/


# Build settings
markdown: kramdown
permalink: pretty
